name: $(Build.DefinitionName)-$(PackageVersion)$(rev:.r)
resources:
- repo: self
  clean: true
  
variables:
  PackageVersion: '0.5.0'
  
phases:
- phase: Phase_1
  displayName: Windows
  condition: succeeded()
  
  queue:
    name: Hosted VS2017
  
  steps:
  - template: azure-steps.yml

- phase: Phase_2
  displayName: Linux
  condition: succeeded()
  
  queue:
    name: Hosted Ubuntu 1604
  
  steps:
  - template: azure-steps.yml

- phase: Phase_3
  displayName: Mac
  condition: succeeded()
  
  queue:
    name: Hosted macOS
  
  steps:
  - template: azure-steps.yml